### ISSUE TITLE
linux support?

### ISSUE THREAD

**Issue by max-mapper** [sandsmark/pdfium#1]
Hi, I am currently trying to compile pdfium for use in gdal on linux (https://gis.stackexchange.com/questions/287589/are-there-working-build-instructions-or-prebuilt-binaries-of-gdal-stable-2-3). I found this repo via the pdfium mailing list. I saw some commits mentioning travis in the past. Is this currently building stable pdfium for linux via travis ci?

**edit** I went ahead and tried on a fork and got this error: https://travis-ci.org/maxogden/pdfium/builds/397616608

**Comment by max-mapper** [comment]
nevermind, found an already working project https://github.com/bblanchon/pdfium-binaries/blob/master/build.sh

**Comment by sandsmark** [comment]
I just use distro packages on Linux.

and the reason I haven't updated this recently is that others provide the same, and have more time to keep their builds up to date.
